extends Node


##
"""
####################################################################################################
TODO
####################################################################################################
REMODELAR OS OBJETOS PARA FICAR MAIS INTUITIVO

COLOCAR NO DATASYSTEM O MODO TUTORIAL

CRIAR OBJETOS PARA DEMONSTRAR AS AÇOES

REFAZER OS BOTÕES DE TECLADO

MEXER NO SISTEMA DE MOSTRAR OS POINTS E EXITS, PERGUNTAR SE AQUELE ITEM JA ESTA ADICIONADO 
E NÃO DESTRUIR TUDO SE NÃO TEVE MUDANÇA

FAZER ANIMAÇÕES DE POINTS SENDO APERTADOS E EXITS ABRINDO

ORGANIZAR O ALGORITMO DO HUMAN PARA PODER NERFAR AS HABILIDADES E PODER BLOQUEAR MOVIMENTOS COM ATAQUES

SISTEMA DE "CORAÇÕES"

FAZER O MINIMAPA NO HUD, TALVEZ PEGAR O ESTADO INICIAL QUANDO TEM A TRANSIÇÃO E CONSTRUIR O MINIMAPA DIRETO

FAZER O MINIMAPA DA PHASE DO MESMO JEITO, AO ACESSAR UMA EXIT DESENHAR A SETA PARA ONDE AQUELA EXIT VAI

FAZER OS STATES REDONDOS AGORA QUE FOI RESOLVIDO AS RAMPAS?

COLOCAR O NUMERO EM CIMA DOS BOTÕES

FAZER MINIMAPA

FAZER MENU DAS FASES

REFATORAR A LÓGICA DO HUMAN PARA PODER SEPARAR AS HABILIDADES PARA PODER NERFAR O PERSONAGEM


SOUND EFFECTS E MUSICA
-ADICIONAR SOM AOS BOTÕES E AO ABRIR EXITS E DOORS

TAMANHO DA TELA, VER ONDE FIXAR OU ALGO ASSIM


FAZER UMA FUNCIONALIDADE PARA QUE CASO APERTE PARA BAIXO + PULO EM CIMA DE UMA PLATAFORMA O BONECO NÃO PULE, 
MAS DESÇA DA PLATAFORMA (NÃO PERMITIR PARA PLATAFORMAS EM 90 GRAUS, 
MELHOR FAZER UM BOJETO SEPARADO PARA ESSA FUNÇÃO DE ONE WAY DOOR)


CONSERTAR A ANIAMÇÃO DE PARADO, POR CONTA DAS RAMPAS QUE FICA COM O PÉ VOANDO


FAZER UM MENU PARA QUANDO APERTAR ESC

DOUBLE JUMP

WALL SLIDE
TEM UMA FUNÇÃO QUE É IS_ON_WALL


CAMERA
LIMITAÇÕES DE CAMERA
CAMERA SMOOTH (?)
CAMERA SHAKE/CAMERA MICRO FREEZE/SLOW MOTION

CRIAR PLATAFORMAS

CRIAR OBSTACULOS
- ESPINHOS
- MAQUINAS DE ATIRAR LASER (FAZEM VOLTAR AO INICIO DO STATE(?))

CRIAR ARMAS QUE ATIRAM E FAZEM VOLTAR AO INIT DO STATE






SFX

MAPA/HUD
PARA O MAPA É NECESSÁRIO FAZER UMA CONTA DE TODOS OS STATES POSSIVEIS E VER A DISTANCIA ENTRE ELES PARA DESENHAR

MENU
- OBTER INFORMAÇÕES PARA VER COMO SALVAR INFO DE FASES E PROGRESSO, VARIAVEIS GLOBAIS ETC
- FAZER UM MENU DAS FASES, DEPOIS DO MAIN_MENU







FAZER O HUMAN GLOBAL DE ALGUMA FORMA, PARA NÃO TER QUE REFERENCIAR EM TODOS OS STATES

CHECAR DE TEMPO EM TEMPO:

- usar mais o set para atualizar valores em nodes

- MASKS E LAYERS
(HUMAN FICA NA LAYER 2 MASK 1, OS OBJETOS QUE SÓ DEVEM INTERAGIR COM ELE O CONTRÁRIO)
(CHEGAR SE É ISSO MESMO)

OBSERVAR O ORDERING ->Z INDEX
HUMAN ESTÁ NO 2 E O RESTO NO 0 POR AGORA
MUDARÁ SE PRECISAR COLOCAR ALGUMA COISA 'A FRENTE' DO HUMAN


####################################################################################################
WORK IN PROGRESS
####################################################################################################





####################################################################################################
DONE
####################################################################################################
DESACOPLAR O INIT DOS STATES PARA PODER MUDAR DE LUGAR

FAZER BOTÕES E PORTAS INTERMEDIÁRIOS PARA ABRIR E FECHAR PASSAGENS

HUD PARA BOTÕES (TUTORIAL)

saidas
//talvez os valores devessem ser associados as saídas, já que podem ter mais de uma
devem mudar de cor quando forem habilitadas
os nexts também devem ser associados as saídas


MUDAR O PULO, DE FORMA QUE SE SOLTAR O BOTÃO DE PULO PARA DE PULAR


TRANSIÇÃO (BLOQUEAR MOVIMENTOS ENTRE STATES)


COYOTE TIME

CRIAR O OBJETO PHASE PARA COLOCAR AS FASES

EDITAR O EXIT PARA PERGUNTAR SE É O FINAL, SE FOR CONCLUIR A FASE

HUD
LISTAR OS BOTOES E SAIDAS E OS VALORES ATUAIS
SERIA BOM LISTAR APENAS OS BOTÕES E SAÍDAS QUE JÁ FORAM LOCALIZADOS
ESCONDER OS VALORES DOS BOTÕES E DAS SAÍDAS ATÉ QUE SE ENTRE NA AREA DELES PELA PRIMEIRA VEZ

COLOCAR O VALOR DE CADA BOTÃO EM UMA CAIXA DE TEXTO SOBRE O BOTÃO E COLCOAR O VALOR ATUAL NO HUD


####################################################################################################
####################################################################################################

&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&
&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&
UM CONCEITO DE PLATFORMVANIA/PLATDROIDVANIA
UMA ESPÉCIE DE METROIDVANIA PORÉM NÃO EM UM MAPA CONTINUO,
MAS NO ESQUEMA DE FASES, COMO SE EM MÁRIO WORLD TIVESSEM SEGREDOS 
QUE SÓ SÃO ACESSÍVEIS DEPOIS DE ADQUIRIR HABILIDADES/FERRAMENTAS
HÁ UM BACKTRACKING NO ESQUEMA DE FASES
MEGAMAN TEM UM POUCO DISSO, PORÉM É MUITO POUCO E GERALMENTE OPCIONAL
&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&
&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&

####################################################################################################
####################################################################################################
"""
##
